# Install git
brew "git"

# Install tmux
brew "tmux"

# Install wezterm
cask "wezterm"

# Install nvim
brew "nvim"

# Install nvm
brew "nvm"

# Install zoxide
brew "zoxide"

# Install stow for symlink
brew "stow"

# Install eazygit
brew install "lazygit"

